version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    depends_on:
      - postgres
